kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: resources
  labels:
    intent: resources
spec:
  storageClassName: "ibmc-file-gold"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: fsf-dal1002b-fz.adn.networklayer.com
    path: /IBM02SEV2071092_121963/data01/resources
